baseurl = "https://paddy.io"
pygmentsuseclasses = true
publishDir = "/home/paddy/go/src/github.com/carvers/infra/nginx/html/paddy.io"

[params]
description = "The personal site of Paddy, an impractical zealot known to tilt at windmills."
