baseurl = "https://paddy.io"
pygmentsuseclasses = true
publishDir = "/home/paddy/projects/infra/files/html/paddy.io"

[params]
description = "The personal site of Paddy, an impractical zealot known to tilt at windmills."
