baseurl = "https://drafts.paddy.io"
pygmentsuseclasses = true
publishDir = "/home/paddy/projects/infra/files/html/drafts.paddy.io"
buildDrafts = true

[params]
description = "The personal site of Paddy, an impractical zealot known to tilt at windmills."
