baseurl = "https://drafts.paddy.carvers.co"
pygmentsuseclasses = true
buildDrafts = true
buildFuture = true

[params]
description = "The personal site of Paddy, an impractical zealot known to tilt at windmills."
