application: kick-more-apm
version: 1
runtime: python
api_version: 1

handlers:
  - url: /core
    static_dir: core
  - url: /extensions
    static_dir: extensions
  - url: /images
    static_dir: images
  - url: /themes
    static_dir: themes
  - url: /jquery-1.7.min.js
    static_files: jquery-1.7.min.js
    upload: jquery-1.7.min.js
  - url: /modernizr.custom.js
    static_files: modernizr.custom.js
    upload: modernizr.custom.js
  - url: /
    static_files: index.html
    upload: index.html
